//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDATCHO
    {
        public int MaChiTietDatCho { get; set; }
        public int MaDatCho { get; set; }
        public int MaKhachHang { get; set; }
    
        public virtual DATCHO DATCHO { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
