//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHUTHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOANHTHUTHANG()
        {
            this.DOANHTHUCHUYENBAYs = new HashSet<DOANHTHUCHUYENBAY>();
        }
    
        public int MaDoanhThuThang { get; set; }
        public int MaDoanhThuNam { get; set; }
        public int Thang { get; set; }
        public int SoChuyenBay { get; set; }
        public decimal DoanhThu { get; set; }
        public decimal TiLe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOANHTHUCHUYENBAY> DOANHTHUCHUYENBAYs { get; set; }
        public virtual DOANHTHUNAM DOANHTHUNAM { get; set; }
    }
}
