//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHUNAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOANHTHUNAM()
        {
            this.DOANHTHUTHANGs = new HashSet<DOANHTHUTHANG>();
        }
    
        public int MaDoanhThuNam { get; set; }
        public int Nam { get; set; }
        public int SoChuyenBay { get; set; }
        public decimal DoanhThu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOANHTHUTHANG> DOANHTHUTHANGs { get; set; }
    }
}
