//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUONGBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUONGBAY()
        {
            this.SANBAYTGs = new HashSet<SANBAYTG>();
            this.CHUYENBAYs = new HashSet<CHUYENBAY>();
        }
    
        public int MaDuongBay { get; set; }
        public int MaSanBayDi { get; set; }
        public int MaSanBayDen { get; set; }
        public int ThoiGianBay { get; set; }
    
        public virtual SANBAY SANBAY { get; set; }
        public virtual SANBAY SANBAY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANBAYTG> SANBAYTGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENBAY> CHUYENBAYs { get; set; }
    }
}
