//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANBAYTG
    {
        public int MaSanBayTG { get; set; }
        public int MaDuongBay { get; set; }
        public int MaSanBay { get; set; }
        public int ThuTu { get; set; }
        public int ThoiGianDung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DUONGBAY DUONGBAY { get; set; }
        public virtual SANBAY SANBAY { get; set; }
    }
}
